version: 2.1

orbs:
  python: circleci/python@2.1.1
  slack: circleci/slack@4.10.1

parameters: #-pp
  manual-trigger-pp:
    type: string
    default: ""
  dbt-vars:
    type: string
    default: "--vars 'test_row_limit: 10'"

commands: #-co
  setup-and-compile-co:
    parameters:
      compile-params:
        description: Optional arguments to be passed to the dbt compile command
        default: ""
        type: string
    steps:
      - checkout
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "starting dbt/meltano installation, and project parse/compile...",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run:
          name: Set up dbt profile
          command: |
            mkdir -p ~/.dbt
            mv .circleci/profiles.yml ~/.dbt/profiles.yml 
            cat  ~/.dbt/profiles.yml
            mv .circleci/requirements.txt  ~/.dbt/requirements.txt
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/.dbt/  # if your requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements. 
      - run:
          name: Run dbt deps
          command: cd dw && dbt deps
      - run:
          name: Install meltano
          command: pipx install "meltano"
      - run:
          name: Install rest api extractor
          command: cd dw-meltano/dw-ownbackup && meltano install extractor tap-rest-api-msdk
      - run:
          name: Install snowflake loader
          command: cd dw-meltano/dw-ownbackup && meltano add loader target-snowflake
      - run:
          name: Run dbt parse
          command: cd dw && dbt parse <<parameters.compile-params>>
      - run:
          name: Run dbt compile
          command: cd dw && dbt compile <<parameters.compile-params>>
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "dbt/meltano installation, and project parse/compile succeeded!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: pass
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "dbt/meltano installation, and project parse/compile failed!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: fail

  extract-and-load-co:
    parameters:
      run-params:
        description: Optional arguments to be passed to the meltano run command
        default: "--exclude tag:hold tag:pit"
        type: string
    steps:
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "starting meltano extract/load...",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run:
          name: Extract json data
          command: cd dw-meltano/dw-ownbackup && meltano run tap-rest-api-msdk target-snowflake
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "meltano extract/load succeeded!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: pass
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "meltano extract/load failed!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: fail

  build-co:
    parameters:
      build-params:
        description: Optional arguments to be passed to the dbt build command
        default: "--exclude tag:hold tag:pit"
        type: string
    steps:
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "starting dbt transform...",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - run:
          name: Run dbt build
          command: cd dw && dbt build <<parameters.build-params>>
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "dbt transform succeeded!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: pass
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "dbt transform failed!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: fail

jobs: #-jb

  setup-and-compile-jb:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - setup-and-compile-co:
          compile-params: ""
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  dbt-sf-runner-daily-jb:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - setup-and-compile-co:
          compile-params: ""
      - extract-and-load-co:
          run-params: ""
      - build-co:
          build-params: "--exclude tag:hold tag:pit"
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  dbt-sf-runner-monthly-pit-jb:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - setup-and-compile-co:
          compile-params: ""
      - build-co:
          build-params: "--exclude tag:hold"
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  dbt-sf-runner-test-jb:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - setup-and-compile-co:
          compile-params: "--target arc_test"
      - build-co:
          build-params: "--target arc_test << pipeline.parameters.dbt-vars >> --exclude tag:hold"
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: basic_success_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
             
workflows: #-wf
  version: 2

  # Setup and compile workflow, triggered upon push to main or development (or manual trigger)
  setup-and-compile-wf:
    when:
      or:
        - equal: [ "setup-and-compile", << pipeline.parameters.manual-trigger-pp >> ]
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - setup-and-compile-jb:
          filters:
            branches:
              only: 
                - main
                - development

  # Daily scheduled workflow for the entire pipeline, excluding monthly PIT tables (or manual trigger)
  scheduled-pipeline-daily-wf: 
    when:
      or:
        - equal: [ "dbt-sf-runner-daily", << pipeline.parameters.manual-trigger-pp >> ]
        - equal: [ "dbt-sf-runner-daily", << pipeline.schedule.name >> ]
    jobs:
      - dbt-sf-runner-daily-jb

  # Monthly scheduled workflow for the entire pipeline, including PIT tables (or manual trigger)
  scheduled-pipeline-monthly-pit-wf:
    when:
      or:
        - equal: [ "dbt-sf-runner-monthly-pit", << pipeline.parameters.manual-trigger-pp >> ]
        - equal: [ "dbt-sf-runner-monthly-pit", << pipeline.schedule.name >> ]
    jobs:
      - dbt-sf-runner-monthly-pit-jb

  # Test scheduled workflow (or manual trigger)
  test-wf:
    when:
      or:
        - equal: [ "dbt-sf-runner-test", << pipeline.parameters.manual-trigger-pp >> ]
        - equal: [ "dbt-sf-runner-test", << pipeline.schedule.name >> ]
    jobs:
      - dbt-sf-runner-test-jb
  