version: 2.1

orbs:
  slack: circleci/slack@4.10.1

parameters: #-pp
  manual-trigger-pp:
    type: string
    default: ""
  dbt-vars:
    type: string
    default: "--vars 'test_row_limit: 10'"

commands: #-co
  setup-and-compile-co:
    parameters:
      compile-params:
        description: Optional arguments to be passed to the dbt compile command
        default: ""
        type: string
    steps:
      - checkout
      - run:
          name: Install dbt
          command: python3 -m pip install dbt-snowflake==1.3.0
      - run:
          name: Set up dbt profile
          command: |
            mkdir -p ~/.dbt
            mv .circleci/profiles.yml ~/.dbt/profiles.yml
            cat  ~/.dbt/profiles.yml
      - run:
          name: Run dbt deps
          command: |
            pip show dbt
          #command: cd dw && dbt deps
      #- run:
          #name: Run dbt parse
          #command: cd dw && dbt parse <<parameters.compile-params>>
      #- run:
          #name: Run dbt compile
          #command: cd dw && dbt compile <<parameters.compile-params>>
  build-co:
    parameters:
      build-params:
        description: Optional arguments to be passed to the dbt build command
        default: "--exclude tag:hold tag:pit"
        type: string
    steps:
      - run:
          name: Run dbt build
          command: cd dw && dbt build <<parameters.build-params>>

jobs:
  setup-and-compile-jb:
    #machine:
      #image: ubuntu-2204:2022.10.1
    docker:
      - image: cimg/python:3.10.8
    steps:
      - setup-and-compile-co:
          compile-params: ""

workflows: #-wf
  version: 2
  setup-and-compile-wf:
    when:
      or:
        - equal: [ "setup-and-compile", << pipeline.parameters.manual-trigger-pp >> ]
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - setup-and-compile-jb:
          filters:
            branches:
              only: 
                - main
                - development
