dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: CCI_TARGET_SNOWFLAKE_ACCOUNT

      # User/password auth
      user: shughes_test
      password: CCI_TARGET_SNOWFLAKE_PASSWORD

      role: public
      database: dw_dev
      warehouse: dw_wh_xs
      schema: dbt_steve
      threads: 4
      client_session_keep_alive: False
      query_tag:

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
