dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: CCI_TARGET_SNOWFLAKE_ACCOUNT
      user: CCI_TARGET_SNOWFLAKE_USER
      password: CCI_TARGET_SNOWFLAKE_PASSWORD
      role: CCI_TARGET_SNOWFLAKE_ROLE
      database: CCI_TARGET_SNOWFLAKE_DBNAME
      warehouse: CCI_TARGET_SNOWFLAKE_WAREHOUSE
      schema: CCI_TARGET_SNOWFLAKE_DBT_SCHEMA
      threads: 4
      client_session_keep_alive: False
      query_tag:

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false
